"""
seed_data.py
Curated open taxonomy seed dataset sourced from Lightcast Open Skills, ESCO,
O*NET Tools & Technology, and Stack Overflow tag ontology.
"""

from typing import List, Dict, Any

TAXONOMY_VERSION = "2026.08.1"

# Curated high-precision tech skills taxonomy
SEED_SKILLS: List[Dict[str, Any]] = [
    # =========================================================================
    # 1. LANGUAGES
    # =========================================================================
    {
        "canonical_name": "Python",
        "category": "language",
        "aliases": ["py", "python3", "python2", "python 3", "python 2", "cpython", "ipython"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "JavaScript",
        "category": "language",
        "aliases": ["js", "es6", "es2020", "es2021", "ecmascript", "javascript es6", "vanilla js"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "TypeScript",
        "category": "language",
        "aliases": ["ts", "type-script", "typescript 4", "typescript 5"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Go",
        "category": "language",
        "aliases": ["golang", "go-lang", "go language"],
        "is_ambiguous": True,  # "Go" needs exact short match protection
        "source": "lightcast",
    },
    {
        "canonical_name": "Rust",
        "category": "language",
        "aliases": ["rust-lang", "rustlang"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "C",
        "category": "language",
        "aliases": ["c language", "c-lang", "c programming", "ansi c"],
        "is_ambiguous": True,  # Single-letter must NEVER match C++ or C#
        "source": "lightcast",
    },
    {
        "canonical_name": "C++",
        "category": "language",
        "aliases": ["cpp", "cplusplus", "c plus plus", "c++11", "c++14", "c++17", "c++20"],
        "is_ambiguous": True,
        "source": "lightcast",
    },
    {
        "canonical_name": "C#",
        "category": "language",
        "aliases": ["csharp", "c sharp", "c-sharp", "cs"],
        "is_ambiguous": True,
        "source": "lightcast",
    },
    {
        "canonical_name": "Java",
        "category": "language",
        "aliases": ["java 8", "java 11", "java 17", "java 21", "core java", "j2se", "jdk"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Ruby",
        "category": "language",
        "aliases": ["ruby-lang", "mri ruby"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "PHP",
        "category": "language",
        "aliases": ["php7", "php8", "php 8", "php-cli"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Swift",
        "category": "language",
        "aliases": ["swift5", "swiftui-lang"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Kotlin",
        "category": "language",
        "aliases": ["kotlin/jvm", "kotlin-native", "kotlin multiplatform"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Scala",
        "category": "language",
        "aliases": ["scala 2", "scala 3"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "R",
        "category": "language",
        "aliases": ["r-lang", "r programming", "r language", "r-project"],
        "is_ambiguous": True,  # Single-letter
        "source": "lightcast",
    },
    {
        "canonical_name": "SQL",
        "category": "language",
        "aliases": ["structured query language", "t-sql", "pl/sql", "ansi sql"],
        "is_ambiguous": True,
        "source": "lightcast",
    },
    {
        "canonical_name": "Bash",
        "category": "language",
        "aliases": ["bash scripting", "shell", "shell script", "shell scripting", "zsh", "sh"],
        "is_ambiguous": False,
        "source": "stackoverflow",
    },
    {
        "canonical_name": "Dart",
        "category": "language",
        "aliases": ["dart-lang", "dartlang"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Elixir",
        "category": "language",
        "aliases": ["elixir-lang", "erlang/elixir"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "HTML/CSS",
        "category": "language",
        "aliases": ["html", "html5", "css", "css3", "html 5", "css 3", "html/css3"],
        "is_ambiguous": False,
        "source": "lightcast",
    },

    # =========================================================================
    # 2. FRAMEWORKS
    # =========================================================================
    {
        "canonical_name": "React",
        "category": "framework",
        "aliases": ["reactjs", "react.js", "react js", "react 18", "react 19"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Next.js",
        "category": "framework",
        "aliases": ["nextjs", "next.js 14", "next.js 15", "next js", "next"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Vue.js",
        "category": "framework",
        "aliases": ["vue", "vuejs", "vue 3", "vue.js 3", "vue 2"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Angular",
        "category": "framework",
        "aliases": ["angularjs", "angular 2+", "angular.js", "angular 17"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "FastAPI",
        "category": "framework",
        "aliases": ["fast-api", "fastapi framework", "fast api"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Django",
        "category": "framework",
        "aliases": ["django-rest-framework", "drf", "django rest framework", "django framework"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Flask",
        "category": "framework",
        "aliases": ["flask framework", "python-flask"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Spring Boot",
        "category": "framework",
        "aliases": ["spring", "springboot", "spring-boot", "spring framework", "spring cloud"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Node.js",
        "category": "framework",
        "aliases": ["nodejs", "node.js", "node js", "node"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Express.js",
        "category": "framework",
        "aliases": ["express", "expressjs", "express.js"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "NestJS",
        "category": "framework",
        "aliases": ["nest.js", "nestjs framework", "nest js"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "ASP.NET Core",
        "category": "framework",
        "aliases": ["asp.net", "aspnetcore", "asp.net core mvc", ".net core", "dotnet core"],
        "is_ambiguous": False,
        "source": "onet",
    },
    {
        "canonical_name": "Ruby on Rails",
        "category": "framework",
        "aliases": ["rails", "ror", "ruby on rails framework"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Tailwind CSS",
        "category": "framework",
        "aliases": ["tailwind", "tailwindcss", "tailwind-css"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Bootstrap",
        "category": "framework",
        "aliases": ["bootstrap 5", "bootstrap4", "twitter bootstrap"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "React Native",
        "category": "framework",
        "aliases": ["react-native", "reactnative", "rn"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Flutter",
        "category": "framework",
        "aliases": ["flutter sdk", "flutter framework"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Svelte",
        "category": "framework",
        "aliases": ["sveltekit", "svelte.js", "svelte-kit"],
        "is_ambiguous": False,
        "source": "lightcast",
    },

    # =========================================================================
    # 3. DATABASES
    # =========================================================================
    {
        "canonical_name": "PostgreSQL",
        "category": "database",
        "aliases": ["postgres", "psql", "postgres database", "postgresql 15", "postgresql 16"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "MySQL",
        "category": "database",
        "aliases": ["my-sql", "mysql 8", "mariadb/mysql"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "MongoDB",
        "category": "database",
        "aliases": ["mongo", "mongodb atlas", "documentdb"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Redis",
        "category": "database",
        "aliases": ["redis cache", "redis cluster", "valkey"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Elasticsearch",
        "category": "database",
        "aliases": ["elastic search", "opensearch", "elk", "elastic stack", "es"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Cassandra",
        "category": "database",
        "aliases": ["apache cassandra", "datastax"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "DynamoDB",
        "category": "database",
        "aliases": ["amazon dynamodb", "aws dynamodb"],
        "is_ambiguous": False,
        "source": "onet",
    },
    {
        "canonical_name": "SQLite",
        "category": "database",
        "aliases": ["sqlite3", "sqlite db"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Snowflake",
        "category": "database",
        "aliases": ["snowflake data warehouse", "snowflake dw", "snowpark"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "BigQuery",
        "category": "database",
        "aliases": ["google bigquery", "gcp bigquery"],
        "is_ambiguous": False,
        "source": "onet",
    },
    {
        "canonical_name": "Neo4j",
        "category": "database",
        "aliases": ["neo-4j", "graph database", "cypher"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Firebase",
        "category": "database",
        "aliases": ["firestore", "firebase realtime db", "firebase auth"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Vector Databases",
        "category": "database",
        "aliases": ["vector db", "pgvector", "pinecone", "qdrant", "chromadb", "weaviate", "milvus"],
        "is_ambiguous": False,
        "source": "lightcast",
    },

    # =========================================================================
    # 4. PLATFORMS & CLOUD INFRASTRUCTURE
    # =========================================================================
    {
        "canonical_name": "AWS",
        "category": "platform",
        "aliases": ["amazon web services", "aws cloud", "ec2", "s3", "lambda", "ecs", "eks"],
        "is_ambiguous": True,
        "source": "lightcast",
    },
    {
        "canonical_name": "GCP",
        "category": "platform",
        "aliases": ["google cloud", "google cloud platform", "gke", "google compute engine"],
        "is_ambiguous": True,
        "source": "lightcast",
    },
    {
        "canonical_name": "Microsoft Azure",
        "category": "platform",
        "aliases": ["azure", "azure cloud", "aks", "azure devops"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Docker",
        "category": "platform",
        "aliases": ["docker-compose", "docker container", "dockerize", "containerization", "dockr"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Kubernetes",
        "category": "platform",
        "aliases": ["k8s", "k8", "kube", "kubernets", "helm", "k8s cluster", "kubernetes administration"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Terraform",
        "category": "platform",
        "aliases": ["hcl", "terraform iac", "opentofu"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Linux",
        "category": "platform",
        "aliases": ["ubuntu", "debian", "centos", "rhel", "red hat linux", "alpine linux", "unix"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Cloudflare",
        "category": "platform",
        "aliases": ["cloudflare workers", "cloudflare r2"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Vercel",
        "category": "platform",
        "aliases": ["vercel deployment", "nextjs vercel"],
        "is_ambiguous": False,
        "source": "lightcast",
    },

    # =========================================================================
    # 5. TOOLS & DEVOPS
    # =========================================================================
    {
        "canonical_name": "Git",
        "category": "tool",
        "aliases": ["git version control", "git-scm"],
        "is_ambiguous": True,
        "source": "lightcast",
    },
    {
        "canonical_name": "GitHub",
        "category": "tool",
        "aliases": ["github actions", "gh actions", "github ci"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "GitLab",
        "category": "tool",
        "aliases": ["gitlab ci", "gitlab-ci", "gitlab pipeline"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Jenkins",
        "category": "tool",
        "aliases": ["jenkins ci", "jenkins pipeline", "jenkinsfile"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Jira",
        "category": "tool",
        "aliases": ["atlassian jira", "jira software"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Postman",
        "category": "tool",
        "aliases": ["postman api", "insomnia", "api testing"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Figma",
        "category": "tool",
        "aliases": ["figma design", "figjam", "ui/ux design in figma"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Spline",
        "category": "tool",
        "aliases": ["spline 3d", "spline design"],
        "is_ambiguous": False,
        "source": "manual",
    },
    {
        "canonical_name": "Kafka",
        "category": "tool",
        "aliases": ["apache kafka", "kafka streaming", "kafka streams", "confluent kafka"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "RabbitMQ",
        "category": "tool",
        "aliases": ["rabbit-mq", "amqp", "message broker"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Celery",
        "category": "tool",
        "aliases": ["celery worker", "python celery"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Ansible",
        "category": "tool",
        "aliases": ["ansible playbook", "ansible automation"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Nginx",
        "category": "tool",
        "aliases": ["nginx reverse proxy", "engine-x", "caddy"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Airflow",
        "category": "tool",
        "aliases": ["apache airflow", "airflow dags", "workflow orchestration"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Apache Spark",
        "category": "tool",
        "aliases": ["spark", "pyspark", "spark streaming", "spark sql"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Prometheus",
        "category": "tool",
        "aliases": ["promql", "prometheus monitoring"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Grafana",
        "category": "tool",
        "aliases": ["grafana dashboards", "observability dashboards"],
        "is_ambiguous": False,
        "source": "lightcast",
    },

    # =========================================================================
    # 6. LIBRARIES & AI/ML
    # =========================================================================
    {
        "canonical_name": "Machine Learning",
        "category": "domain",
        "aliases": ["ml", "supervised learning", "unsupervised learning", "predictive modeling"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Deep Learning",
        "category": "domain",
        "aliases": ["dl", "neural networks", "ann", "cnn", "rnn", "transformers"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "PyTorch",
        "category": "library",
        "aliases": ["pytorch", "torch", "pytorh", "torchvision", "torchaudio"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "TensorFlow",
        "category": "library",
        "aliases": ["tf", "tensorflow 2", "keras", "tf.keras"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "scikit-learn",
        "category": "library",
        "aliases": ["sklearn", "scikit learn", "sci-kit learn"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Pandas",
        "category": "library",
        "aliases": ["pandas dataframe", "python pandas"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "NumPy",
        "category": "library",
        "aliases": ["numpy array", "python numpy"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "OpenCV",
        "category": "library",
        "aliases": ["cv2", "computer vision library", "opencv-python"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Roboflow",
        "category": "tool",
        "aliases": ["roboflow universe", "roboflow annotation"],
        "is_ambiguous": False,
        "source": "manual",
    },
    {
        "canonical_name": "Manim",
        "category": "library",
        "aliases": ["manimce", "manim animation"],
        "is_ambiguous": False,
        "source": "manual",
    },
    {
        "canonical_name": "LangChain",
        "category": "library",
        "aliases": ["langchain framework", "langgraph", "langsmith"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "LlamaIndex",
        "category": "library",
        "aliases": ["llama-index", "gpt-index"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Hugging Face",
        "category": "library",
        "aliases": ["huggingface", "transformers library", "diffusers", "datasets library"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Matplotlib",
        "category": "library",
        "aliases": ["pyplot", "matplotlib.pyplot", "seaborn"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Colab",
        "category": "tool",
        "aliases": ["google colab", "google colaboratory", "jupyter", "jupyter notebook", "jupyterlab"],
        "is_ambiguous": False,
        "source": "lightcast",
    },

    # =========================================================================
    # 7. DOMAINS & ARCHITECTURE
    # =========================================================================
    {
        "canonical_name": "Microservices",
        "category": "domain",
        "aliases": ["microservice architecture", "micro-services", "service-oriented architecture", "soa"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "System Design",
        "category": "domain",
        "aliases": ["distributed systems", "high availability", "scalability", "architectural design"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "CI/CD",
        "category": "domain",
        "aliases": ["continuous integration", "continuous deployment", "ci / cd", "ci", "cd"],
        "is_ambiguous": True,
        "source": "lightcast",
    },
    {
        "canonical_name": "REST APIs",
        "category": "domain",
        "aliases": ["rest", "restful", "rest api", "restful api", "web apis"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "GraphQL",
        "category": "domain",
        "aliases": ["graphql api", "apollo graphql", "relay"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "gRPC",
        "category": "domain",
        "aliases": ["protobuf", "protocol buffers", "grpc framework"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "WebSockets",
        "category": "domain",
        "aliases": ["socket.io", "realtime sockets", "websocket server"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Computer Vision",
        "category": "domain",
        "aliases": ["cv", "image processing", "object detection", "yolo", "segmentation"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Natural Language Processing",
        "category": "domain",
        "aliases": ["nlp", "text processing", "ner", "sentiment analysis", "llm", "large language models"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Prompt Engineering",
        "category": "domain",
        "aliases": ["prompt design", "in-context learning", "chain-of-thought", "rag", "retrieval augmented generation"],
        "is_ambiguous": False,
        "source": "manual",
    },
    {
        "canonical_name": "MLOps",
        "category": "domain",
        "aliases": ["ml-ops", "machine learning operations", "model monitoring", "model deployment"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "Cybersecurity",
        "category": "domain",
        "aliases": ["infosec", "appsec", "penetration testing", "oauth", "jwt", "zero trust"],
        "is_ambiguous": False,
        "source": "lightcast",
    },
    {
        "canonical_name": "UI/UX",
        "category": "domain",
        "aliases": ["ui", "ux", "user interface", "user experience", "user research", "wireframing", "prototyping"],
        "is_ambiguous": True,
        "source": "lightcast",
    },
    {
        "canonical_name": "Agile",
        "category": "domain",
        "aliases": ["scrum", "kanban", "sprint planning", "agile development", "standup"],
        "is_ambiguous": False,
        "source": "esco",
    },
    {
        "canonical_name": "TDD",
        "category": "domain",
        "aliases": ["test-driven development", "unit testing", "pytest", "jest", "cypress", "integration testing"],
        "is_ambiguous": True,
        "source": "esco",
    },


    # =========================================================================
    # 8. SOFT SKILLS & LEADERSHIP
    # =========================================================================
    {
        "canonical_name": "Cross-functional Leadership",
        "category": "soft_skill",
        "aliases": ["team leadership", "technical mentorship", "leading teams", "team management"],
        "is_ambiguous": False,
        "source": "esco",
    },
    {
        "canonical_name": "Technical Writing",
        "category": "soft_skill",
        "aliases": ["documentation", "rfc writing", "system documentation", "api documentation"],
        "is_ambiguous": False,
        "source": "esco",
    },
    {
        "canonical_name": "Stakeholder Management",
        "category": "soft_skill",
        "aliases": ["client communication", "product alignment", "executive reporting"],
        "is_ambiguous": False,
        "source": "esco",
    },
    {
        "canonical_name": "Problem Solving",
        "category": "soft_skill",
        "aliases": ["analytical skills", "troubleshooting", "root cause analysis", "debugging"],
        "is_ambiguous": False,
        "source": "esco",
    }
]
