#!/bin/sh
set -eu
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -v runtime_password="$ATS_RUNTIME_DATABASE_PASSWORD" <<'SQL'
SELECT format('CREATE ROLE ats_runtime LOGIN PASSWORD %L', :'runtime_password') \gexec
CREATE SCHEMA IF NOT EXISTS ats_v2;
GRANT USAGE ON SCHEMA ats_v2 TO ats_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA ats_v2 GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO ats_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA ats_v2 GRANT USAGE,SELECT ON SEQUENCES TO ats_runtime;
SQL
