import {
  StatMetric,
  WeeklyData,
  AIMatchRate,
  PipelineCandidateItem,
  JobRequisition,
  CandidateDetail,
  ActiveUpload,
  CompletedUpload,
  UploadIssue,
} from "@/types/ats";

export const MOCK_STATS: StatMetric[] = [
  {
    id: "active_jobs",
    label: "ACTIVE JOBS",
    value: "50",
    change: "Across 8 Domains",
    trend: "positive",
    icon: "briefcase",
    style: "default",
  },
  {
    id: "candidates",
    label: "CANDIDATES",
    value: "1,247",
    change: "+89 vs last month",
    trend: "positive",
    icon: "users",
    style: "default",
  },
  {
    id: "avg_time_to_hire",
    label: "AVG TIME-TO-HIRE",
    value: "18",
    unit: "days",
    change: "-2 days improved",
    trend: "positive",
    icon: "clock",
    style: "default",
  },
  {
    id: "open_offers",
    label: "OPEN OFFERS",
    value: "3",
    change: "Awaiting signatures",
    trend: "neutral",
    icon: "award",
    style: "highlighted_dark",
  },
];

export const MOCK_WEEKLY_DATA: WeeklyData[] = [
  { week: "W1", count: 42, is_peak: false },
  { week: "W2", count: 58, is_peak: false },
  { week: "W3", count: 39, is_peak: false },
  { week: "W4", count: 82, is_peak: false },
  { week: "W5", count: 64, is_peak: false },
  { week: "W6", count: 90, is_peak: false },
  { week: "W7", count: 128, is_peak: true },
  { week: "W8", count: 73, is_peak: false },
];

export const MOCK_AI_MATCH_RATE: AIMatchRate = {
  rate: 68,
  precision_label: "Candidate fit score precision",
  matched_percent: 68,
  not_matched_percent: 32,
};

export const MOCK_PIPELINE: Record<string, PipelineCandidateItem[]> = {
  Contacted: [
    {
      id: "cand-001",
      name: "Priya Sharma",
      role: "Senior Backend Engineer",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80",
      match_score: 92,
      summary: "Strong system design skills. Ex-Stripe, scalable microservices...",
      stage: "Contacted",
      applied_time: "2 days ago",
    },
    {
      id: "cand-002",
      name: "David Chen",
      role: "Product Manager",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
      match_score: 88,
      summary: "Focus on user-centric fintech products. Messaged on LinkedIn,...",
      stage: "Contacted",
      applied_time: "3 days ago",
    },
  ],
  Interview: [
    {
      id: "cand-004",
      name: "Marcus Adebayo",
      role: "Lead UX Researcher",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
      match_score: 95,
      summary: "Nailed the cultural fit round. Technical presentation schedule...",
      stage: "Interview",
      applied_time: "5 days ago",
    },
    {
      id: "cand-005",
      name: "Elena Jimenez",
      role: "Data Scientist",
      avatar: "EJ",
      match_score: 84,
      summary: "Passed initial coding screen. Needs deeper evaluation on...",
      stage: "Interview",
      applied_time: "1 week ago",
    },
  ],
  Negotiation: [
    {
      id: "cand-006",
      name: "Robert Vance",
      role: "VP of Engineering",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80",
      match_score: 98,
      summary: "Offer sent out yesterday. Discussing equity structure and...",
      stage: "Negotiation",
      probability: 80,
      applied_time: "2 weeks ago",
    },
  ],
};

const SAMPLE_AVATARS = [
  "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
  "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
  "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80",
  "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
  "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80",
  "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80",
];

export const MOCK_JOBS: JobRequisition[] = [
  // 1. AI, Machine Learning & Intelligent Systems
  {
    id: "job-001",
    title: "Generative AI Developer",
    department: "AI & Intelligent Systems",
    location: "Remote / San Francisco",
    status: "OPEN",
    posted_date: "Feb 10",
    candidates_count: 28,
    avatars: [SAMPLE_AVATARS[0], SAMPLE_AVATARS[1], SAMPLE_AVATARS[2]],
    top_match: { score: 96, label: "96 Top Match", last_run: "2h ago", status: "ACTIVE" },
    icon_type: "ai",
    job_description: "Builds applications using LLMs, prompt frameworks, and vector databases. Designs retrieval-augmented generation (RAG) pipelines, fine-tunes embeddings, and integrates cutting-edge foundation models into production systems.",
    min_years_experience: 3.0,
    required_skills: ["LLMs", "LangChain", "LlamaIndex", "Vector Databases", "Prompt Engineering", "Python", "RAG", "Embeddings"],
  },
  {
    id: "job-002",
    title: "AI/ML Engineer",
    department: "AI & Intelligent Systems",
    location: "New York / Hybrid",
    status: "OPEN",
    posted_date: "Feb 08",
    candidates_count: 34,
    avatars: [SAMPLE_AVATARS[3], SAMPLE_AVATARS[4], SAMPLE_AVATARS[5]],
    top_match: { score: 94, label: "94 Top Match", last_run: "3h ago", status: "ACTIVE" },
    icon_type: "ai",
    job_description: "Designs and develops core machine learning models and predictive algorithms. Trains, optimizes, and evaluates statistical and deep learning architectures for enterprise workloads.",
    min_years_experience: 4.0,
    required_skills: ["PyTorch", "TensorFlow", "Scikit-learn", "Python", "Machine Learning", "Predictive Modeling", "Deep Learning", "MLOps"],
  },
  {
    id: "job-003",
    title: "MLOps Engineer",
    department: "AI & Intelligent Systems",
    location: "Remote",
    status: "OPEN",
    posted_date: "Feb 05",
    candidates_count: 19,
    avatars: [SAMPLE_AVATARS[0], SAMPLE_AVATARS[2]],
    top_match: { score: 91, label: "91 Top Match", last_run: "1d ago", status: "ACTIVE" },
    icon_type: "ai",
    job_description: "Deploys, monitors, and manages the lifecycle of machine learning pipelines. Establishes automated CI/CD for ML models, drift detection, feature stores, and containerized GPU serving.",
    min_years_experience: 4.0,
    required_skills: ["MLflow", "Kubeflow", "Docker", "Kubernetes", "CI/CD", "Model Monitoring", "Python", "Feature Stores"],
  },
  {
    id: "job-004",
    title: "NLP Engineer",
    department: "AI & Intelligent Systems",
    location: "Boston / Remote",
    status: "OPEN",
    posted_date: "Feb 01",
    candidates_count: 15,
    avatars: [SAMPLE_AVATARS[1], SAMPLE_AVATARS[3]],
    top_match: { score: 89, label: "89 Top Match", last_run: "5h ago", status: "ACTIVE" },
    icon_type: "ai",
    job_description: "Specializes in machine comprehension of human language, chatbots, and translation systems. Implements transformer models, tokenization pipelines, sentiment analysis, and NER.",
    min_years_experience: 3.0,
    required_skills: ["NLP", "Hugging Face", "Transformers", "NLTK", "Spacy", "Python", "Text Processing", "Tokenization"],
  },
  {
    id: "job-005",
    title: "Computer Vision Engineer",
    department: "AI & Intelligent Systems",
    location: "Seattle / Hybrid",
    status: "OPEN",
    posted_date: "Jan 28",
    candidates_count: 22,
    avatars: [SAMPLE_AVATARS[4], SAMPLE_AVATARS[5]],
    top_match: { score: 93, label: "93 Top Match", last_run: "1d ago", status: "ACTIVE" },
    icon_type: "ai",
    job_description: "Processes visual data for autonomous systems, robotics, and facial recognition. Develops real-time object detection, segmentation, and 3D point cloud processing pipelines.",
    min_years_experience: 4.0,
    required_skills: ["OpenCV", "YOLO", "PyTorch", "Image Processing", "Object Detection", "C++", "Python", "CUDA"],
  },
  {
    id: "job-006",
    title: "AI Product Manager",
    department: "AI & Intelligent Systems",
    location: "San Francisco, CA",
    status: "OPEN",
    posted_date: "Jan 25",
    candidates_count: 18,
    avatars: [SAMPLE_AVATARS[0], SAMPLE_AVATARS[4]],
    top_match: { score: 90, label: "90 Top Match", last_run: "4h ago", status: "ACTIVE" },
    icon_type: "product",
    job_description: "Bridges technical AI development teams with business strategy and user needs. Translates generative AI and machine learning capabilities into high-impact user experiences and measurable business metrics.",
    min_years_experience: 4.0,
    required_skills: ["AI Product Strategy", "Model Evaluation", "User Experience", "Roadmapping", "Agile", "Cross-functional Leadership"],
  },
  {
    id: "job-007",
    title: "Data Labeling & Annotation Specialist",
    department: "AI & Intelligent Systems",
    location: "Remote",
    status: "OPEN",
    posted_date: "Jan 20",
    candidates_count: 12,
    avatars: [SAMPLE_AVATARS[1], SAMPLE_AVATARS[2]],
    top_match: { score: 86, label: "86 Top Match", last_run: "2d ago", status: "ACTIVE" },
    icon_type: "ai",
    job_description: "Curates, cleans, and structures training datasets for high-performance AI models. Establishes gold-standard annotation guidelines, multi-modal labelling workflows, and active learning validation.",
    min_years_experience: 1.0,
    required_skills: ["Data Annotation", "Quality Assurance", "CVAT", "Label Studio", "Dataset Curation", "Data Cleaning"],
  },
  {
    id: "job-008",
    title: "AI Ethics & Compliance Officer",
    department: "AI & Intelligent Systems",
    location: "Washington, DC / Remote",
    status: "OPEN",
    posted_date: "Jan 18",
    candidates_count: 9,
    avatars: [SAMPLE_AVATARS[3], SAMPLE_AVATARS[5]],
    top_match: { score: 88, label: "88 Top Match", last_run: "1d ago", status: "ACTIVE" },
    icon_type: "security",
    job_description: "Ensures corporate AI applications adhere to legal, fairness, and safety standards. Conducts algorithmic bias auditing, regulatory impact assessments (EU AI Act, NIST AI RMF), and responsible AI guidelines.",
    min_years_experience: 5.0,
    required_skills: ["AI Governance", "Compliance", "Bias Auditing", "Risk Assessment", "GDPR", "Responsible AI"],
  },

  // 2. Cloud, DevOps & Infrastructure
  {
    id: "job-009",
    title: "Cloud Architect",
    department: "Cloud & Infrastructure",
    location: "Remote / Austin, TX",
    status: "OPEN",
    posted_date: "Feb 12",
    candidates_count: 21,
    avatars: [SAMPLE_AVATARS[0], SAMPLE_AVATARS[1]],
    top_match: { score: 95, label: "95 Top Match", last_run: "1h ago", status: "ACTIVE" },
    icon_type: "cloud",
    job_description: "Designs overarching cloud strategy, migration plans, and multi-cloud architectures. Optimizes cloud cost, reliability, security, and hybrid-cloud topologies.",
    min_years_experience: 7.0,
    required_skills: ["AWS", "Azure", "GCP", "Cloud Architecture", "Terraform", "Well-Architected Framework", "Microservices"],
  },
  {
    id: "job-010",
    title: "Cloud Engineer",
    department: "Cloud & Infrastructure",
    location: "Denver, CO / Hybrid",
    status: "OPEN",
    posted_date: "Feb 09",
    candidates_count: 31,
    avatars: [SAMPLE_AVATARS[2], SAMPLE_AVATARS[3]],
    top_match: { score: 92, label: "92 Top Match", last_run: "3h ago", status: "ACTIVE" },
    icon_type: "cloud",
    job_description: "Manages everyday infrastructure deployment and provisioning across AWS, Azure, or GCP. Builds automated serverless and containerized cloud resources.",
    min_years_experience: 3.0,
    required_skills: ["AWS", "Azure", "Linux", "Terraform", "CloudFormation", "Networking", "Docker"],
  },
  {
    id: "job-011",
    title: "DevOps Engineer",
    department: "Cloud & Infrastructure",
    location: "Remote",
    status: "OPEN",
    posted_date: "Feb 06",
    candidates_count: 42,
    avatars: [SAMPLE_AVATARS[4], SAMPLE_AVATARS[5], SAMPLE_AVATARS[0]],
    top_match: { score: 94, label: "94 Top Match", last_run: "2h ago", status: "ACTIVE" },
    icon_type: "cloud",
    job_description: "Builds automated CI/CD pipelines to bridge software development and IT operations. Implements infrastructure as code, release automation, and environment consistency.",
    min_years_experience: 4.0,
    required_skills: ["Jenkins", "GitHub Actions", "Docker", "Kubernetes", "CI/CD", "Bash", "Ansible", "Git"],
  },
  {
    id: "job-012",
    title: "Platform Engineer",
    department: "Cloud & Infrastructure",
    location: "San Francisco / Remote",
    status: "OPEN",
    posted_date: "Feb 02",
    candidates_count: 16,
    avatars: [SAMPLE_AVATARS[1], SAMPLE_AVATARS[2]],
    top_match: { score: 90, label: "90 Top Match", last_run: "6h ago", status: "ACTIVE" },
    icon_type: "cloud",
    job_description: "Designs and maintains internal developer platforms (IDPs) to speed up coding workflows. Provides self-service tooling, Golden Paths, and standardized runtime environments for product engineering.",
    min_years_experience: 5.0,
    required_skills: ["Kubernetes", "Terraform", "Backstage", "GitOps", "Helm", "Developer Tooling", "Golang"],
  },
  {
    id: "job-013",
    title: "Site Reliability Engineer (SRE)",
    department: "Cloud & Infrastructure",
    location: "Remote / New York",
    status: "OPEN",
    posted_date: "Jan 29",
    candidates_count: 25,
    avatars: [SAMPLE_AVATARS[3], SAMPLE_AVATARS[4]],
    top_match: { score: 93, label: "93 Top Match", last_run: "5h ago", status: "ACTIVE" },
    icon_type: "cloud",
    job_description: "Focuses on system availability, automation, and large-scale infrastructure resilience. Implements SLOs/SLAs, distributed tracing, automated incident remediation, and blameless post-mortems.",
    min_years_experience: 5.0,
    required_skills: ["SRE", "Prometheus", "Grafana", "Distributed Systems", "Incident Management", "Python", "Chaos Engineering"],
  },
  {
    id: "job-014",
    title: "Network Architect",
    department: "Cloud & Infrastructure",
    location: "Dallas, TX",
    status: "OPEN",
    posted_date: "Jan 22",
    candidates_count: 11,
    avatars: [SAMPLE_AVATARS[5], SAMPLE_AVATARS[0]],
    top_match: { score: 87, label: "87 Top Match", last_run: "1d ago", status: "ACTIVE" },
    icon_type: "cloud",
    job_description: "Designs high-performance local, wide-area, and cloud-integrated enterprise communication networks. Configures SD-WAN, BGP peering, and multi-cloud interconnects.",
    min_years_experience: 8.0,
    required_skills: ["BGP", "OSPF", "SD-WAN", "Cloud Interconnects", "Network Design", "VPN", "Cisco / Juniper"],
  },
  {
    id: "job-015",
    title: "Network Engineer",
    department: "Cloud & Infrastructure",
    location: "Chicago, IL",
    status: "OPEN",
    posted_date: "Jan 19",
    candidates_count: 19,
    avatars: [SAMPLE_AVATARS[1], SAMPLE_AVATARS[3]],
    top_match: { score: 85, label: "85 Top Match", last_run: "2d ago", status: "ACTIVE" },
    icon_type: "cloud",
    job_description: "Installs, configures, and maintains physical and virtual network hardware and routing systems. Troubleshoots routing protocols, firewall rules, and enterprise switches.",
    min_years_experience: 3.0,
    required_skills: ["Routing & Switching", "Firewalls", "VLANs", "TCP/IP", "DNS", "Wireshark", "Troubleshooting"],
  },
  {
    id: "job-016",
    title: "Systems Administrator",
    department: "Cloud & Infrastructure",
    location: "Atlanta, GA",
    status: "OPEN",
    posted_date: "Jan 14",
    candidates_count: 27,
    avatars: [SAMPLE_AVATARS[2], SAMPLE_AVATARS[4]],
    top_match: { score: 88, label: "88 Top Match", last_run: "1d ago", status: "ACTIVE" },
    icon_type: "cloud",
    job_description: "Manages local servers, operating systems, hardware setups, and core digital office infrastructure. Maintains virtualized clusters, directory services, and system patch management.",
    min_years_experience: 3.0,
    required_skills: ["Linux", "Windows Server", "Active Directory", "VMware", "Bash/PowerShell", "Backup Recovery"],
  },

  // 3. Data Science, Analytics & Big Data
  {
    id: "job-017",
    title: "Data Scientist",
    department: "Data Science & Analytics",
    location: "Remote / New York",
    status: "OPEN",
    posted_date: "Feb 14",
    candidates_count: 48,
    avatars: [SAMPLE_AVATARS[0], SAMPLE_AVATARS[1], SAMPLE_AVATARS[3]],
    top_match: { score: 95, label: "95 Top Match", last_run: "1h ago", status: "ACTIVE" },
    icon_type: "database",
    job_description: "Combines statistics, programming, and modeling to extract business value and build predictive logic. Performs exploratory data analysis, hypothesis testing, and algorithmic feature engineering.",
    min_years_experience: 3.0,
    required_skills: ["Python", "R", "Statistical Modeling", "Machine Learning", "SQL", "Data Visualization", "Pandas"],
  },
  {
    id: "job-018",
    title: "Data Engineer",
    department: "Data Science & Analytics",
    location: "San Francisco / Hybrid",
    status: "OPEN",
    posted_date: "Feb 11",
    candidates_count: 39,
    avatars: [SAMPLE_AVATARS[2], SAMPLE_AVATARS[4], SAMPLE_AVATARS[5]],
    top_match: { score: 93, label: "93 Top Match", last_run: "3h ago", status: "ACTIVE" },
    icon_type: "database",
    job_description: "Creates data pipelines, architecture, and ETL systems to process massive datasets. Designs scalable batch and streaming data pipelines with workflow orchestrators.",
    min_years_experience: 4.0,
    required_skills: ["Apache Spark", "Airflow", "SQL", "Python", "ETL Pipelines", "Snowflake", "Data Lakehouse"],
  },
  {
    id: "job-019",
    title: "Analytics Engineer",
    department: "Data Science & Analytics",
    location: "Remote",
    status: "OPEN",
    posted_date: "Feb 07",
    candidates_count: 26,
    avatars: [SAMPLE_AVATARS[1], SAMPLE_AVATARS[3]],
    top_match: { score: 91, label: "91 Top Match", last_run: "4h ago", status: "ACTIVE" },
    icon_type: "database",
    job_description: "Prepares, cleans, and structures data within warehouses for seamless business analysis. Writes version-controlled transformation models using dbt and modern data warehouse techniques.",
    min_years_experience: 3.0,
    required_skills: ["dbt", "SQL", "BigQuery", "Snowflake", "Data Modeling", "Git", "Metabase"],
  },
  {
    id: "job-020",
    title: "Business Intelligence (BI) Analyst",
    department: "Data Science & Analytics",
    location: "Chicago / Remote",
    status: "OPEN",
    posted_date: "Feb 03",
    candidates_count: 35,
    avatars: [SAMPLE_AVATARS[0], SAMPLE_AVATARS[4]],
    top_match: { score: 89, label: "89 Top Match", last_run: "6h ago", status: "ACTIVE" },
    icon_type: "database",
    job_description: "Translates structured data into actionable executive dashboards and corporate reports. Partners with business leaders to track core KPIs, revenue drivers, and operational metrics.",
    min_years_experience: 2.0,
    required_skills: ["Power BI", "Tableau", "Advanced SQL", "DAX", "Dashboard Design", "KPI Reporting"],
  },
  {
    id: "job-021",
    title: "Big Data Architect",
    department: "Data Science & Analytics",
    location: "Seattle, WA",
    status: "OPEN",
    posted_date: "Jan 27",
    candidates_count: 14,
    avatars: [SAMPLE_AVATARS[2], SAMPLE_AVATARS[5]],
    top_match: { score: 94, label: "94 Top Match", last_run: "1d ago", status: "ACTIVE" },
    icon_type: "database",
    job_description: "Designs large-scale data storage and compute environments using tools like Hadoop or Spark. Implements high-throughput distributed ingestion and lakehouse architecture.",
    min_years_experience: 7.0,
    required_skills: ["Hadoop", "Apache Spark", "Kafka", "Distributed Computing", "Delta Lake", "Architecture Design"],
  },
  {
    id: "job-022",
    title: "Database Administrator (DBA)",
    department: "Data Science & Analytics",
    location: "Remote / Phoenix",
    status: "OPEN",
    posted_date: "Jan 21",
    candidates_count: 17,
    avatars: [SAMPLE_AVATARS[1], SAMPLE_AVATARS[4]],
    top_match: { score: 87, label: "87 Top Match", last_run: "2d ago", status: "ACTIVE" },
    icon_type: "database",
    job_description: "Manages, protects, and tunes the performance of relational and non-relational databases. Leads indexing optimization, high availability clustering, replication, and backup disaster recovery.",
    min_years_experience: 5.0,
    required_skills: ["PostgreSQL", "MySQL", "Query Optimization", "Database Replication", "Backup & Recovery", "Index Tuning"],
  },
  {
    id: "job-023",
    title: "Data Governance Specialist",
    department: "Data Science & Analytics",
    location: "New York, NY",
    status: "OPEN",
    posted_date: "Jan 16",
    candidates_count: 13,
    avatars: [SAMPLE_AVATARS[3], SAMPLE_AVATARS[0]],
    top_match: { score: 86, label: "86 Top Match", last_run: "2d ago", status: "ACTIVE" },
    icon_type: "database",
    job_description: "Enforces corporate data policies, privacy standards, and data cataloging rules. Maintains data lineage, metadata definitions, and compliance with privacy regulations.",
    min_years_experience: 4.0,
    required_skills: ["Data Governance", "Collibra", "GDPR/CCPA Compliance", "Data Lineage", "Metadata Management", "Data Quality"],
  },

  // 4. Cybersecurity & Risk Management
  {
    id: "job-024",
    title: "Cybersecurity Analyst",
    department: "Cybersecurity & Risk",
    location: "Remote / Washington, DC",
    status: "OPEN",
    posted_date: "Feb 13",
    candidates_count: 33,
    avatars: [SAMPLE_AVATARS[0], SAMPLE_AVATARS[2]],
    top_match: { score: 92, label: "92 Top Match", last_run: "2h ago", status: "ACTIVE" },
    icon_type: "security",
    job_description: "Monitors corporate networks for active threats and mitigates digital security breaches. Analyzes SIEM alerts, triages suspicious network anomalies, and enforces defense-in-depth controls.",
    min_years_experience: 2.0,
    required_skills: ["SIEM", "Incident Response", "Network Security", "Threat Hunting", "Log Analysis", "Firewalls"],
  },
  {
    id: "job-025",
    title: "Ethical Hacker / Penetration Tester",
    department: "Cybersecurity & Risk",
    location: "Remote",
    status: "OPEN",
    posted_date: "Feb 09",
    candidates_count: 24,
    avatars: [SAMPLE_AVATARS[1], SAMPLE_AVATARS[5]],
    top_match: { score: 96, label: "96 Top Match", last_run: "4h ago", status: "ACTIVE" },
    icon_type: "security",
    job_description: "Proactively attacks internal networks to discover and patch structural vulnerabilities. Performs authorized red-team engagements, exploit chaining, and web/network penetration testing.",
    min_years_experience: 4.0,
    required_skills: ["Penetration Testing", "Metasploit", "Burp Suite", "Vulnerability Assessment", "Kali Linux", "Exploit Development"],
  },
  {
    id: "job-026",
    title: "Application Security Engineer",
    department: "Cybersecurity & Risk",
    location: "San Francisco / Remote",
    status: "OPEN",
    posted_date: "Feb 04",
    candidates_count: 20,
    avatars: [SAMPLE_AVATARS[3], SAMPLE_AVATARS[4]],
    top_match: { score: 91, label: "91 Top Match", last_run: "1d ago", status: "ACTIVE" },
    icon_type: "security",
    job_description: "Ensures that custom software code and APIs are secure before deployment. Embeds SAST/DAST into CI/CD pipelines, performs threat modeling, and trains developers in secure coding practices.",
    min_years_experience: 4.0,
    required_skills: ["AppSec", "OWASP Top 10", "SAST/DAST", "Threat Modeling", "Secure Code Review", "API Security"],
  },
  {
    id: "job-027",
    title: "Cloud Security Specialist",
    department: "Cybersecurity & Risk",
    location: "Remote / Seattle",
    status: "OPEN",
    posted_date: "Jan 30",
    candidates_count: 27,
    avatars: [SAMPLE_AVATARS[0], SAMPLE_AVATARS[3]],
    top_match: { score: 94, label: "94 Top Match", last_run: "5h ago", status: "ACTIVE" },
    icon_type: "security",
    job_description: "Focuses entirely on securing cloud architecture, access keys, and virtual networks. Implements Cloud Security Posture Management (CSPM), identity boundaries, and automated compliance policies.",
    min_years_experience: 4.0,
    required_skills: ["AWS Security", "IAM", "Cloud Custodian", "CSPM", "GuardDuty", "Zero Trust", "Compliance"],
  },
  {
    id: "job-028",
    title: "Identity and Access Management (IAM) Engineer",
    department: "Cybersecurity & Risk",
    location: "Remote",
    status: "OPEN",
    posted_date: "Jan 24",
    candidates_count: 18,
    avatars: [SAMPLE_AVATARS[1], SAMPLE_AVATARS[2]],
    top_match: { score: 89, label: "89 Top Match", last_run: "1d ago", status: "ACTIVE" },
    icon_type: "security",
    job_description: "Controls user permissions, single sign-on (SSO), and digital identity authentication. Implements zero-trust access control, privilege management, and directory federations.",
    min_years_experience: 4.0,
    required_skills: ["Okta", "Ping Identity", "SAML", "OAuth 2.0 / OIDC", "Active Directory", "Zero Trust Architecture"],
  },
  {
    id: "job-029",
    title: "Security Operations Center (SOC) Manager",
    department: "Cybersecurity & Risk",
    location: "Austin, TX / Hybrid",
    status: "OPEN",
    posted_date: "Jan 17",
    candidates_count: 15,
    avatars: [SAMPLE_AVATARS[4], SAMPLE_AVATARS[5]],
    top_match: { score: 93, label: "93 Top Match", last_run: "2d ago", status: "ACTIVE" },
    icon_type: "security",
    job_description: "Leads the real-time threat incident response team and defensive strategy. Oversees 24/7 detection, threat hunting operations, runbook automation, and executive breach escalation.",
    min_years_experience: 6.0,
    required_skills: ["SOC Leadership", "Incident Response", "SIEM", "Threat Intelligence", "Team Management", "Forensic Analysis"],
  },
  {
    id: "job-030",
    title: "Chief Information Security Officer (CISO)",
    department: "Cybersecurity & Risk",
    location: "New York / Executive",
    status: "OPEN",
    posted_date: "Jan 10",
    candidates_count: 8,
    avatars: [SAMPLE_AVATARS[0], SAMPLE_AVATARS[1]],
    top_match: { score: 97, label: "97 Top Match", last_run: "1d ago", status: "ACTIVE" },
    icon_type: "leadership",
    job_description: "Directs the entire cybersecurity vision, risk budgeting, and security compliance of an enterprise. Presents cyber risks to the Board of Directors and aligns security investments with business objectives.",
    min_years_experience: 10.0,
    required_skills: ["Information Security Strategy", "Risk Management", "ISO 27001", "SOC 2", "Executive Leadership", "Budgeting"],
  },

  // 5. Software Engineering & Digital Design
  {
    id: "job-031",
    title: "Full-Stack Developer",
    department: "Software Engineering",
    location: "Remote",
    status: "OPEN",
    posted_date: "Feb 15",
    candidates_count: 52,
    avatars: [SAMPLE_AVATARS[0], SAMPLE_AVATARS[2], SAMPLE_AVATARS[4]],
    top_match: { score: 95, label: "95 Top Match", last_run: "1h ago", status: "ACTIVE" },
    icon_type: "code",
    job_description: "Handles both visual frontend interfaces and server-side backend product logic. Develops end-to-end features, data schemas, REST/GraphQL APIs, and responsive web components.",
    min_years_experience: 3.0,
    required_skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "REST APIs", "Tailwind CSS", "Docker"],
  },
  {
    id: "job-032",
    title: "Backend Developer",
    department: "Software Engineering",
    location: "Remote / San Francisco",
    status: "OPEN",
    posted_date: "Feb 12",
    candidates_count: 46,
    avatars: [SAMPLE_AVATARS[1], SAMPLE_AVATARS[3], SAMPLE_AVATARS[5]],
    top_match: { score: 94, label: "94 Top Match", last_run: "2h ago", status: "ACTIVE" },
    icon_type: "code",
    job_description: "Architects data storage, server logic, and robust APIs that power applications. Focuses on concurrency, database indexing, caching strategies, and resilient microservice communication.",
    min_years_experience: 3.0,
    required_skills: ["Python", "FastAPI", "PostgreSQL", "Redis", "Microservices", "REST/gRPC", "Docker"],
  },
  {
    id: "job-033",
    title: "Frontend Developer",
    department: "Software Engineering",
    location: "Remote / New York",
    status: "OPEN",
    posted_date: "Feb 08",
    candidates_count: 41,
    avatars: [SAMPLE_AVATARS[2], SAMPLE_AVATARS[4]],
    top_match: { score: 92, label: "92 Top Match", last_run: "3h ago", status: "ACTIVE" },
    icon_type: "code",
    job_description: "Codes user-facing web interfaces using frameworks like React, Vue, or Angular. Champions responsive layouts, accessibility (WCAG), state management, and modern CSS architecture.",
    min_years_experience: 3.0,
    required_skills: ["React", "TypeScript", "Next.js", "CSS/Tailwind", "Web Performance", "State Management"],
  },
  {
    id: "job-034",
    title: "Mobile App Developer",
    department: "Software Engineering",
    location: "Remote / Los Angeles",
    status: "OPEN",
    posted_date: "Feb 05",
    candidates_count: 29,
    avatars: [SAMPLE_AVATARS[0], SAMPLE_AVATARS[5]],
    top_match: { score: 90, label: "90 Top Match", last_run: "5h ago", status: "ACTIVE" },
    icon_type: "code",
    job_description: "Creates native or cross-platform applications for iOS and Android devices. Builds responsive mobile user interfaces, offline data sync, push notifications, and App Store releases.",
    min_years_experience: 3.0,
    required_skills: ["React Native", "Flutter", "Swift", "Kotlin", "Mobile UX", "App Store Deployment"],
  },
  {
    id: "job-035",
    title: "Embedded Systems Engineer",
    department: "Software Engineering",
    location: "San Jose / Hybrid",
    status: "OPEN",
    posted_date: "Jan 31",
    candidates_count: 16,
    avatars: [SAMPLE_AVATARS[1], SAMPLE_AVATARS[3]],
    top_match: { score: 88, label: "88 Top Match", last_run: "1d ago", status: "ACTIVE" },
    icon_type: "emerging",
    job_description: "Writes software for physical hardware like IoT chips, automotive sensors, and smart appliances. Develops low-level firmware, driver interfaces, and real-time operating system tasks.",
    min_years_experience: 4.0,
    required_skills: ["C", "C++", "RTOS", "Microcontrollers (ARM/STM32)", "Hardware Protocols (I2C/SPI/UART)", "Firmware"],
  },
  {
    id: "job-036",
    title: "API Engineer",
    department: "Software Engineering",
    location: "Remote",
    status: "OPEN",
    posted_date: "Jan 26",
    candidates_count: 22,
    avatars: [SAMPLE_AVATARS[2], SAMPLE_AVATARS[4]],
    top_match: { score: 91, label: "91 Top Match", last_run: "6h ago", status: "ACTIVE" },
    icon_type: "code",
    job_description: "Specializes in designing, documenting, and securing microservices communication channels. Implements API gateways, rate limiting, OpenAPI specifications, and developer documentation.",
    min_years_experience: 4.0,
    required_skills: ["OpenAPI/Swagger", "gRPC", "GraphQL", "REST", "Rate Limiting", "API Gateways", "Kong"],
  },
  {
    id: "job-037",
    title: "UI/UX Designer",
    department: "Software Engineering",
    location: "London / Remote",
    status: "OPEN",
    posted_date: "Jan 20",
    candidates_count: 37,
    avatars: [SAMPLE_AVATARS[0], SAMPLE_AVATARS[1], SAMPLE_AVATARS[3]],
    top_match: { score: 93, label: "93 Top Match", last_run: "2h ago", status: "ACTIVE" },
    icon_type: "design",
    job_description: "Conducts user research and creates intuitive interfaces to optimize digital products. Develops design systems, interactive prototypes, user journey maps, and conducts usability testing.",
    min_years_experience: 3.0,
    required_skills: ["Figma", "UI/UX Design", "User Research", "Prototyping", "Wireframing", "Design Systems"],
  },

  // 6. Quality Assurance, Automation & Support
  {
    id: "job-038",
    title: "QA Automation Engineer",
    department: "Quality Assurance & Support",
    location: "Remote",
    status: "OPEN",
    posted_date: "Feb 11",
    candidates_count: 30,
    avatars: [SAMPLE_AVATARS[2], SAMPLE_AVATARS[5]],
    top_match: { score: 92, label: "92 Top Match", last_run: "3h ago", status: "ACTIVE" },
    icon_type: "qa",
    job_description: "Writes test scripts to automatically find bugs and check software performance. Creates end-to-end regression suites, performance benchmarks, and CI/CD automated test gates.",
    min_years_experience: 3.0,
    required_skills: ["Cypress", "Playwright", "Selenium", "Python", "TypeScript", "CI/CD Test Automation", "TestNG"],
  },
  {
    id: "job-039",
    title: "Manual QA Tester",
    department: "Quality Assurance & Support",
    location: "Remote",
    status: "OPEN",
    posted_date: "Feb 06",
    candidates_count: 25,
    avatars: [SAMPLE_AVATARS[0], SAMPLE_AVATARS[4]],
    top_match: { score: 86, label: "86 Top Match", last_run: "1d ago", status: "ACTIVE" },
    icon_type: "qa",
    job_description: "Visually tests software workflows to catch usability issues from a human perspective. Designs comprehensive test plans, executes exploratory test rounds, and logs detailed reproduction steps in Jira.",
    min_years_experience: 2.0,
    required_skills: ["Manual Testing", "Test Case Design", "Bug Tracking (Jira)", "Usability Testing", "Exploratory Testing"],
  },
  {
    id: "job-040",
    title: "IT Support Specialist (Help Desk)",
    department: "Quality Assurance & Support",
    location: "Chicago / On-site",
    status: "OPEN",
    posted_date: "Jan 29",
    candidates_count: 32,
    avatars: [SAMPLE_AVATARS[1], SAMPLE_AVATARS[3]],
    top_match: { score: 84, label: "84 Top Match", last_run: "2d ago", status: "ACTIVE" },
    icon_type: "qa",
    job_description: "Troubleshoots everyday hardware, software, and access issues for employees or clients. Configures workstations, resolves ticket escalations, and manages endpoint software deployment.",
    min_years_experience: 1.0,
    required_skills: ["Technical Support", "Jira Service Management", "macOS/Windows Troubleshooting", "Hardware Setup", "Customer Service"],
  },
  {
    id: "job-041",
    title: "Technical Writer",
    department: "Quality Assurance & Support",
    location: "Remote",
    status: "OPEN",
    posted_date: "Jan 23",
    candidates_count: 14,
    avatars: [SAMPLE_AVATARS[4], SAMPLE_AVATARS[5]],
    top_match: { score: 89, label: "89 Top Match", last_run: "1d ago", status: "ACTIVE" },
    icon_type: "qa",
    job_description: "Drafts developer documentation, user manuals, and API guides for technical clarity. Maintains docs-as-code repos, architecture diagrams, and onboarding guides for engineering teams.",
    min_years_experience: 2.0,
    required_skills: ["API Documentation", "Markdown", "Git", "Technical Communication", "Docs-as-Code", "SDK Guides"],
  },

  // 7. Tech Leadership, Product & Business Strategy
  {
    id: "job-042",
    title: "Product Manager",
    department: "Tech Leadership & Strategy",
    location: "San Francisco / Hybrid",
    status: "OPEN",
    posted_date: "Feb 14",
    candidates_count: 44,
    avatars: [SAMPLE_AVATARS[0], SAMPLE_AVATARS[1], SAMPLE_AVATARS[2]],
    top_match: { score: 95, label: "95 Top Match", last_run: "1h ago", status: "ACTIVE" },
    icon_type: "product",
    job_description: "Defines the long-term vision, features, and release roadmap of software products. Gathers user requirements, prioritizes backlogs, and aligns cross-functional engineering and go-to-market teams.",
    min_years_experience: 4.0,
    required_skills: ["Product Strategy", "Roadmap Planning", "User Story Mapping", "Agile/Scrum", "Data Analysis", "Feature Prioritization"],
  },
  {
    id: "job-043",
    title: "Scrum Master / Agile Coach",
    department: "Tech Leadership & Strategy",
    location: "Remote",
    status: "OPEN",
    posted_date: "Feb 07",
    candidates_count: 21,
    avatars: [SAMPLE_AVATARS[3], SAMPLE_AVATARS[4]],
    top_match: { score: 88, label: "88 Top Match", last_run: "4h ago", status: "ACTIVE" },
    icon_type: "leadership",
    job_description: "Facilitates team workflows, removes blockers, and speeds up product delivery cycles. Leads sprint planning, retrospectives, and coaches engineering teams in Agile best practices.",
    min_years_experience: 4.0,
    required_skills: ["Scrum", "Kanban", "Agile Coaching", "Jira", "Sprint Facilitation", "Continuous Improvement"],
  },
  {
    id: "job-044",
    title: "Technical Project Manager (TPM)",
    department: "Tech Leadership & Strategy",
    location: "Seattle / Hybrid",
    status: "OPEN",
    posted_date: "Feb 01",
    candidates_count: 28,
    avatars: [SAMPLE_AVATARS[5], SAMPLE_AVATARS[0]],
    top_match: { score: 91, label: "91 Top Match", last_run: "1d ago", status: "ACTIVE" },
    icon_type: "leadership",
    job_description: "Manages engineering timelines, resource budgets, and cross-team dependencies. Drives complex technical deliveries from conception through launch with precise risk management.",
    min_years_experience: 5.0,
    required_skills: ["Technical Project Management", "Timeline Estimation", "Risk Management", "Cross-team Coordination", "Resource Planning"],
  },
  {
    id: "job-045",
    title: "Enterprise Architect",
    department: "Tech Leadership & Strategy",
    location: "New York / Hybrid",
    status: "OPEN",
    posted_date: "Jan 25",
    candidates_count: 12,
    avatars: [SAMPLE_AVATARS[1], SAMPLE_AVATARS[4]],
    top_match: { score: 93, label: "93 Top Match", last_run: "2d ago", status: "ACTIVE" },
    icon_type: "leadership",
    job_description: "Strategizes the overarching tech ecosystem to align IT capabilities with business goals. Evaluates emerging technologies, governs enterprise standards, and guides long-term cloud transformation.",
    min_years_experience: 9.0,
    required_skills: ["Enterprise Architecture", "TOGAF", "Cloud Modernization", "Legacy Integration", "Strategic Planning", "Governance"],
  },
  {
    id: "job-046",
    title: "IT Business Analyst",
    department: "Tech Leadership & Strategy",
    location: "Remote / Boston",
    status: "OPEN",
    posted_date: "Jan 18",
    candidates_count: 23,
    avatars: [SAMPLE_AVATARS[2], SAMPLE_AVATARS[3]],
    top_match: { score: 87, label: "87 Top Match", last_run: "2d ago", status: "ACTIVE" },
    icon_type: "leadership",
    job_description: "Evaluates company processes to determine technological solutions for operational problems. Documents business requirements, models workflows (BPMN), and performs gap analysis.",
    min_years_experience: 3.0,
    required_skills: ["Business Requirements Analysis", "Process Mapping", "BPMN", "SQL", "Stakeholder Management", "Gap Analysis"],
  },
  {
    id: "job-047",
    title: "Chief Technology Officer (CTO)",
    department: "Tech Leadership & Strategy",
    location: "San Francisco / Executive",
    status: "OPEN",
    posted_date: "Jan 12",
    candidates_count: 9,
    avatars: [SAMPLE_AVATARS[0], SAMPLE_AVATARS[5]],
    top_match: { score: 98, label: "98 Top Match", last_run: "1d ago", status: "ACTIVE" },
    icon_type: "leadership",
    job_description: "Outlines the macro technology strategy and drives innovation across the entire organization. Mentors engineering leaders, oversees technical due diligence, and steers technical vision.",
    min_years_experience: 12.0,
    required_skills: ["Technology Strategy", "Executive Leadership", "Architecture Governance", "Talent Building", "R&D", "Venture Strategy"],
  },

  // 8. Specialized & Emerging Domains
  {
    id: "job-048",
    title: "IoT Engineer",
    department: "Specialized & Emerging Domains",
    location: "Austin, TX / Hybrid",
    status: "OPEN",
    posted_date: "Feb 10",
    candidates_count: 18,
    avatars: [SAMPLE_AVATARS[1], SAMPLE_AVATARS[2]],
    top_match: { score: 91, label: "91 Top Match", last_run: "5h ago", status: "ACTIVE" },
    icon_type: "emerging",
    job_description: "Develops and connects smart networks of physical sensors, edge devices, and cloud backends. Implements MQTT telemetry pipelines, edge compute models, and device fleet security.",
    min_years_experience: 4.0,
    required_skills: ["IoT Protocols (MQTT/CoAP)", "Edge Computing", "AWS IoT / Azure IoT", "Microcontrollers", "Python/C++", "Device Provisioning"],
  },
  {
    id: "job-049",
    title: "RPA Developer",
    department: "Specialized & Emerging Domains",
    location: "Remote",
    status: "OPEN",
    posted_date: "Feb 04",
    candidates_count: 22,
    avatars: [SAMPLE_AVATARS[3], SAMPLE_AVATARS[4]],
    top_match: { score: 89, label: "89 Top Match", last_run: "1d ago", status: "ACTIVE" },
    icon_type: "emerging",
    job_description: "Builds robotic process automation bots to handle repetitive, manual office tasks. Automates multi-application workflows, OCR document extraction, and desktop automation.",
    min_years_experience: 3.0,
    required_skills: ["UiPath", "Automation Anywhere", "Process Automation", "VB.NET/C#", "Workflow Orchestration", "OCR"],
  },
  {
    id: "job-050",
    title: "Salesforce / CRM Administrator",
    department: "Specialized & Emerging Domains",
    location: "Remote / Dallas",
    status: "OPEN",
    posted_date: "Jan 28",
    candidates_count: 31,
    avatars: [SAMPLE_AVATARS[0], SAMPLE_AVATARS[5]],
    top_match: { score: 90, label: "90 Top Match", last_run: "2d ago", status: "ACTIVE" },
    icon_type: "emerging",
    job_description: "Optimizes and configures customer relationship management software to match sales pipelines. Builds custom Flow automations, user permissions, object schemas, and sales reports.",
    min_years_experience: 3.0,
    required_skills: ["Salesforce Administration", "Flow Automation", "Apex Basics", "CRM Customization", "User Roles & Security", "Reports & Dashboards"],
  },
];

export const MOCK_CANDIDATE_PRIYA: CandidateDetail = {
  id: "cand-001",
  name: "Priya Sharma",
  anonymized_name: "Candidate #7712",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
  target_headline: "Senior Backend Engineer",
  role: "Senior Backend Engineer",
  location: "San Francisco, CA",
  email: "priya.s@example.com",
  phone: "(415) 555-0192",
  linkedin: "linkedin.com/in/priyas",
  status: "Interviewing",
  stage: "Interviewing",
  applied_date: "2 days ago",
  applied_for_job: "Senior Interface Designer",
  years_of_experience: 8.0,
  highest_education: "M.S. Computer Science, Stanford University",
  core_skills: ["Python", "Kubernetes", "PostgreSQL", "FastAPI", "AWS", "Go"],
  experience: [
    {
      role: "Staff Engineer",
      company: "Stripe",
      period: "2021 — Present",
      description:
        "Led core payments idempotency microservices and latency optimization for global transaction routing.",
    },
    {
      role: "Senior Engineer",
      company: "Uber",
      period: "2018 — 2021",
      description:
        "Designed real-time geospatial driver dispatch ingestion microservices with Go and Kafka.",
    },
  ],
  scorecard: {
    overall_match_score: 95,
    match_tier: "Exceptional Match",
    model_version: "Model gemma2:2b",
    evaluated_at: "Evaluated 2h ago",
    categories: [
      {
        name: "Technical Depth",
        score: 9.2,
        max_score: 10.0,
        quote:
          "Led migration of monolith to FastAPI microservices, reducing p99 latency by 40%. Implemented robust idempotency keys for distributed payments...",
        source_ref: "View source ¶12",
      },
      {
        name: "System Design",
        score: 8.5,
        max_score: 10.0,
        quote:
          "Strong evidence of distributed systems design, specifically regarding eventual consistency and partitioned PostgreSQL shards.",
        source_ref: "View source ¶8",
      },
      {
        name: "Leadership",
        score: 7.0,
        max_score: 10.0,
        quote:
          "Mentored 3 junior engineers. Solid team contributor, but less evidence of cross-functional strategic planning.",
        source_ref: "View source ¶19",
      },
    ],
    risk_flags: [
      "No explicit evidence of managing Kubernetes clusters at enterprise scale (mentions usage, not administration).",
    ],
    suggested_questions: [
      "Can you describe a specific time you had to debug a failing Kubernetes pod in production?",
      "How do you handle schema migrations across multiple deployed microservices?",
    ],
    team_notes: [
      {
        id: "note-1",
        author: "Alex Rivet",
        initials: "AR",
        role: "Admin",
        timestamp: "Yesterday at 2:14 PM",
        content:
          "Looks like a very strong technical fit. @Sarah can you drill into the Kubernetes experience during the system design loop?",
      },
    ],
  },
};

export const MOCK_ACTIVE_UPLOADS: ActiveUpload[] = [
  {
    id: "up-1",
    filename: "jdoe_resume_2024.pdf",
    taskId: "TSK-8829",
    statusLabel: "PROCESSING • 70%",
    progress: 70,
    currentStep: "LLM Extract",
  },
  {
    id: "up-2",
    filename: "asmith_cv_final.pdf",
    taskId: "TSK-8830",
    statusLabel: "SCRUBBING PII • 40%",
    progress: 40,
    currentStep: "PII Scrub",
  },
];

export const MOCK_COMPLETED_UPLOADS: CompletedUpload[] = [
  {
    id: "comp-1",
    filename: "mjohnson_marketing.pdf",
    taskId: "TSK-8828",
    duration: "12.4s",
    candidateId: "cand-001",
  },
];

export const MOCK_ISSUES: UploadIssue[] = [
  {
    id: "iss-1",
    filename: "corrupt.pdf",
    status: "retrying",
    message: "Retrying... attempt 2/5",
    attempt: "2/5",
    nextRetryIn: "8s",
  },
  {
    id: "iss-2",
    filename: "scan_issue.pdf",
    status: "failed",
    message: "Failed after 5 attempts. Unreadable text layer.",
    attempt: "5/5",
  },
];
